### PR TITLE
added 2 courses that are not ML focused

### PR DESCRIPTION
**Pull request by fatmaf**
Added courses that are not ML focused

### CODE REVIEW

**Comment by anasayubi** [comment]
Thanks a lot for the contribution!

**Comment by anasayubi** [comment]
I feel that a bit of formatting is required. Plus putting both of the courses under the same heading might be better as well. Furthermore, as most beginners are unaware of the difference between Machine learning and AI, I feel that we need to give a brief description of that difference under the heading of "Holistic AI Courses"
Btw the heading "Holistic AI Courses" is not the same size as the sub heading "Mathematics". And putting AI in the table will make it more searchable as well.

Just putting my thoughts out on how to make it better!

**Comment by fatmaf** [comment]
Good points. I'll do that when I get time next but feel free to
change/add/remove stuff from it in the meantime :)

**Comment by anasayubi** [comment]
Definitely!

**Pull request merged**
